# Generated by Django 5.1.4 on 2025-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDatabase',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admindatabase',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('DSA', 'DSA'), ('OOP', 'OOP'), ('Software Engineering', 'Software Engineering'), ('DBMS', 'DBMS'), ('Web Dev', 'Web Dev'), ('Operating Systems', 'Operating Systems'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Cloud Computing', 'Cloud Computing'), ('Distributed Systems', 'Distributed Systems'), ('Blockchain Tech', 'BlockChain Tech')], max_length=100)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userdatabase',
            },
        ),
    ]
